import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import Nav from "@/components/nav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Jimmy Blog",
  description: "Generated by Jimmy Blog",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const customTheme = {
    token:{
      // borderRadiusLG:12
    },
    components: {
      Card: {
        bodyPadding:0,
        borderRadius:0,
      },
    },
  };
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AntdRegistry>
          <ConfigProvider theme={customTheme}>
            <Nav></Nav>
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
